name: Configure pyenv and pick the right version
on: [push, pull_request]

jobs:
 # python installtion
  install-python:
  # should run on linux based operating system
    runs-on: windows-latest
  
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2.3.1
      - name: Install python version
        with:
          python-version: 3.8.6 # pick 3.8.6 verion 
          
      - name: Install dependencies
        run: pip install pyoxidizer
        
      - name: build
        run: cd withimportlib && pyoxidizer build exe
